### ISSUE TITLE
Consider using dead-key rather than Unicode combining characters to produce accented characters.

### ISSUE THREAD

**Issue by springcomp** [tbolon/optimized-azerty-win#5]
Currently, the layout uses Unicode combining diacritics to implement various special characters. I think this is incorrect and the norm specifies that the behaviour of those keys must match the current behavior of the <kbd>^</kbd> key on current AZERTY keyboards.

This means that, say, <kbd>^</kbd> must be a dead-key, instead of being an active key that produces a Unicode combining character.

For instance, although directly available from the keyboard layout, the `é` (LATIN SMALL LETTER E WITH ACUTE ACCENT) can also be input using the following combination: <kbd>e</kbd>, <kbd>AltGr</kbd>+<kbd>é</kbd> from the layout in the current version of the source code.

I recommend to make use of dead-key instead.

Therefore, with my proposition, typing the `é` character would be possible using the combination <kbd>AltGr</kbd>+<kbd>é</kbd>, <kbd>e</kbd>.

The difference lies in the order in which the keys are typed. For a dead-key, the user must first type the desired accent using the appopriate dead-key, and then the key corresponding to the character to be modified. This is consistent with the behavior of existing AZERTY keyboards.

On the other hand, using a Unicode combining character allows for greater flexibility because one is able to produce characters that would normally not be available. For instance, using combining characters, one would be able to type a `ẽ́` (LATIN SMALL LETTER E, COMBINING TILDE, COMBINING ACUTE ACCENT).

I believe one must strive for simplicity and match the behavior of existing AZERTY keyboards. Therefore, my proposition is to use dead-key instead.

**Comment by tbolon** [comment]
You are right about that.

Initially I only used Unicode diacritics because it was the easier way to publish a version quickly.

Of course, dead-key are the real expected behavior, but as it will require a lot of work, I decided to publish a rough version, then implement the dead-key combination after that, or let people contribute to the project to add them.

We can let this issue open, or create a new one as a checklist with all dead-keys of the layout, or even create one issue for each dead-key.

Feel free to suggest a solution if you want.
